server.servlet.context-path = /spring-example-jwt-auth
spring.application.name = spring-example-jwt-auth
spring.banner.location = classpath:banner.txt
server.servlet.encoding.charset = UTF-8

jwt-auth.client-secret = insira aqui o client secret da API
jwt-auth.client-id = ${spring.application.name}